version: "3"
services:
    ofd-db:
        container_name: postgres
        image: postgres
        restart: always
        env_file:
            - sql/database.env
        ports:
            - '5432:5432'
        

    main_app:
        container_name: fastapi
        build: ./main
        command: ./main/boot.sh
        restart: always
        depends_on: 
            - 'ofd-db'
            - 'redis-server'
        ports:
            - 8000:8000

    
    redis-server:
        container_name: redis
        restart: always
        image: redis
        ports:
            - '6379:6379'